# Generated by Django 5.2.4 on 2025-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
