# Generated by Django 5.2.4 on 2025-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_interest'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='interests_tags', to='blog.tag'),
        ),
    ]
