# Generated by Django 5.2.4 on 2025-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='00:00:00', unique=True),
            preserve_default=False,
        ),
    ]
