# Generated by Django 5.2.4 on 2025-08-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_author_article_owner_podcast_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
